// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8eKqIVfmTd_WrptqumheOV9qXbOukESQ',
    appId: '1:543429835590:web:6c1a9033969e019f674347',
    messagingSenderId: '543429835590',
    projectId: 'ulearning-app-24bf0',
    authDomain: 'ulearning-app-24bf0.firebaseapp.com',
    storageBucket: 'ulearning-app-24bf0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALc8bXvWThF2v1DditITjU-hPsps1Hxqo',
    appId: '1:543429835590:android:bdddfdd9972a77f9674347',
    messagingSenderId: '543429835590',
    projectId: 'ulearning-app-24bf0',
    storageBucket: 'ulearning-app-24bf0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8TVd_-S6QEOAc956CwQQt-L4LjzCWGPo',
    appId: '1:543429835590:ios:b750a8b56e8905d8674347',
    messagingSenderId: '543429835590',
    projectId: 'ulearning-app-24bf0',
    storageBucket: 'ulearning-app-24bf0.firebasestorage.app',
    iosBundleId: 'com.example.ulearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8TVd_-S6QEOAc956CwQQt-L4LjzCWGPo',
    appId: '1:543429835590:ios:b750a8b56e8905d8674347',
    messagingSenderId: '543429835590',
    projectId: 'ulearning-app-24bf0',
    storageBucket: 'ulearning-app-24bf0.firebasestorage.app',
    iosBundleId: 'com.example.ulearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8eKqIVfmTd_WrptqumheOV9qXbOukESQ',
    appId: '1:543429835590:web:fa59014ffe272d49674347',
    messagingSenderId: '543429835590',
    projectId: 'ulearning-app-24bf0',
    authDomain: 'ulearning-app-24bf0.firebaseapp.com',
    storageBucket: 'ulearning-app-24bf0.firebasestorage.app',
  );

}